### ISSUE TITLE
Failure to comply with Apache License 2.0 for copied code

### ISSUE THREAD

**Issue by strazzere** [DrizzleRisk/drizzleDumper#1]
It would appear you forgot to follow Apache License 2.0 for all the code you seem to have... "borrowed" without mentioning that you borrowed it;

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

Feel free to look at my repo, which contains code that was obviously used. :)

https://github.com/strazzere/android-unpacker/tree/master/native-unpacker

**Comment by DrizzleRisk** [comment]
I used to mentioned in my article that I have borrowed some of your code (http://www.freebuf.com/sectool/105147.html), but i'am sorry for not mentioned it in my project , i just update it.

By the way , your code has an error:
from:
https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/kisskiss.c#L248
to:
https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/kisskiss.c#L232

-1 is bool true

**Comment by strazzere** [comment]
Ah, thats more of a remnant from previous code. According to standards, `0` is `false` and `1` is `true`. However I was attempting to pass back a different number for a specific error. However, that `if` check will still only pass if the returned value is `true` (1).
