### ISSUE TITLE
我是小白 想问一下如何编译

### ISSUE THREAD

**Issue by lozn00** [DrizzleRisk/drizzleDumper#3]
我使用idea cloin编译找不到导入的东西
compilation terminated.
CMakeFiles/drizzleDumper_master.dir/build.make:62: recipe for target 'CMakeFiles/drizzleDumper_master.dir/drizzleDumper.c.o' failed
make[3]: *** [CMakeFiles/drizzleDumper_master.dir/drizzleDumper.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/drizzleDumper_master.dir/all' failed
make[2]: *** [CMakeFiles/drizzleDumper_master.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/drizzleDumper_master.dir/rule' failed
make[1]: *** [CMakeFiles/drizzleDumper_master.dir/rule] Error 2
Makefile:118: recipe for target 'drizzleDumper_master' failed
make: *** [drizzleDumper_master] Error 2

**Comment by lozn00** [comment]
[ 50%] Building C object CMakeFiles/drizzleDumper_master.dir/drizzleDumper.c.o
In file included from /cygdrive/f/src/c_compiler_path/drizzleDumper-master1/drizzleDumper-master/drizzleDumper.c:6:0:
/cygdrive/f/src/c_compiler_path/drizzleDumper-master1/drizzleDumper-master/drizzleDumper.h:14:24: fatal error: sys/ptrace.h: No such file or directory
 #include <sys/ptrace.h>

**Comment by DrizzleRisk** [comment]
NDK直接编译
